name: roadmap
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
  codegenLoader: flutter pub run easy_localization:generate -O lib/localizations -S translations -f json
  localeKeys: flutter pub run easy_localization:generate -O lib/localizations -S translations  -f keys -o locale_keys.g.dart
  icon: flutter pub run flutter_launcher_icons:main
  splash: flutter pub run flutter_native_splash:create

scripts:
  build: $runner build --delete-conflicting-outputs
  watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
  easy_localization: $codegenLoader & $localeKeys
  change_icon: $get & $icon
  change_splash: $get & $splash

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1
  easy_localization: ^3.0.1
  theme_provider: ^0.5.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  dio: ^4.0.6
  bot_toast: ^4.0.2
  sizer: ^2.0.15
  google_fonts: ^3.0.1
  reactive_forms: ^13.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  google_sign_in: ^5.3.3
  webview_flutter: ^3.0.4
  infinite_scroll_pagination: ^3.2.0
  font_awesome_flutter: ^10.1.0
  material_floating_search_bar: ^0.3.7
  salomon_bottom_bar: ^3.3.1
  graphview: ^1.1.1
  flutter_reaction_button: ^2.0.1+1
  image_picker: ^0.8.5+3

dev_dependencies:
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo_710x599.png"
  image_path_ios: "assets/logo_1024x1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground_432x432.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logo_foreground_432x432.png
  color_dark: "#161616"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/logo_foreground_432x432.png
  #android: false
  #ios: false
  #web: false
  #android_gravity: center
  #web_image_mode: center
  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - translations/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
